version: '3.8'

services:
  monitoring-system:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    env_file:
      - .env.prod
    volumes:
      - ./call_recordings:/app/call_recordings
      - ./extracted_data:/app/extracted_data
      - ./logs:/app/logs
    restart: unless-stopped
    
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped
